### ISSUE TITLE
Allow custom booking ID

### ISSUE THREAD

**Issue by TadeasKula** [awethemes/awebooking#40]
I would like to see a possibility to change a reservation ID. Because of the accountancy we have to have a specific FORMAT and SEQUENCE. And IF one booking (ID) is for some reason deleted, the ID number should be available again for another booking.

**Comment by anhskohbo** [comment]
For now, you can't re-use prev deleted ID is because we use increment ID.
Any idea for this?

**Comment by TadeasKula** [comment]
Well, we don't care much about booking id in a database, but we need to show a customer the right code. So if the id is 237352, thats ok, but customer and we at the backend have to see a correct sequence like this 20170001, 20170002, 20170003... and if reservation with number 20170002 is canceled, than it should be used again.
