### ISSUE TITLE
Option to add more "people tariffs"

### ISSUE THREAD

**Issue by TadeasKula** [awethemes/awebooking#41]
We offer three tariffs: Adults, Children and Seniors. I desperately need to add the Seniors. It doesn't have to be created just like "Senior", but for example just a option to add more people tariffs to the pricing.

**Comment by anhskohbo** [comment]
@ndoublehwp, tell me what we can need todo to implement this into core?

**Comment by TadeasKula** [comment]
Basically it’s the same thing as tariff adults.

1) Option to book like 3 seniors and 1 child, 4 seniors, 2 adults and 2 seniors… in frontend, same thing in the backend
2) Working with same capacity as adults
3) Just to be able to see it everywhere (booking process in frontend, reservations in backend, availability manager, emails,…)

Really appriciate your wok! Thank you

**Comment by TadeasKula** [comment]
But that's my problem. You can view it from the view of more of your customers and do this like a feature, that you can add any other tariff and just assign a logic behind it (similar as the newest addon)

But my guess is, that this would be harder to implement.

**Comment by ndoublehwp** [comment]
@anhskohbo 
- AweBooking Settings > Guests
- Add new inputs into Admin Room type.
- Add new inputs into Check availability form and Single form.
- Add query hook when handling forms (check in frontend, add, edit, remove booking, single check availability,    ).
- Fix Admin Booking.
- Fix API email and email templates.
- Fix Booking infomation page.
- Fix Booking cart template.
- Fix Check-out template.

And all add-ons for AweBooking :)

**Comment by TadeasKula** [comment]
Sounds very good!

I'm really looking forward!

**Comment by anhskohbo** [comment]
Some serious issues about database from prev release that cause this will be put in beta11 instead beta10.

**Comment by TadeasKula** [comment]
I understand, thanks for an update
