### ISSUE TITLE
Few more strings to translate in Admin

### ISSUE THREAD

**Issue by TadeasKula** [awethemes/awebooking#44]
Admin reservation page:
"Add new" (Add New Reservation)
"updated" (Reservation updated.)
"Total:" (Total: 4,410 Kč)
"Number of infants"
" %s infants " (1 infant)

Admin availability page:
"%.. nights, from %.. to %.." (3 nights nights, from 2017-12-13 to 2017-12-16)

Admin price page:
"From" and "To"
same from availability - "%.. nights, from %.. to %.." (3 nights nights, from 2017-12-13 to 2017-12-16)

Settings:
"Children bookable?"
"Write some thing about this, eg: Ages 2 - 12."
"Infants bookable?"
"Write some thing about this, eg: Under 2."

And we use Hillter, so there are also Infants:
"Infants"

I don't say these string are not in .pot file, but I translated them and they do not reflect in backend.

**Comment by anhskohbo** [comment]
Yes, some strings in admin write under hard code :D

**Comment by TadeasKula** [comment]
Hello,

I edited this issue to be up to date. Thanks for some .pot updates!
