### ISSUE TITLE
Option to add a notice to Rules

### ISSUE THREAD

**Issue by TadeasKula** [awethemes/awebooking#47]
Just an idea from a UX view.

If I successfully disabled any other bookings than with check-in on Monday, and check-out on Sunday, but I would also like to give a user reason why the room is not showing. So a option to add reason why something is happening using a yellow box above checking availability would be nice feature to add.

This is not urgent, but just an idea to make Rules even better :)

**Comment by anhskohbo** [comment]
This already in our plan, will release in next (or fews) week. We busy now for "icalendar" addon.
