### ISSUE TITLE
Shipping with woocomerce

### ISSUE THREAD

**Issue by itsSilver** [awethemes/awebooking#55]
Hi there, 
i updated to latest version of woocommerce 3.2.1 and beta10 and everything works fine except shipping fields on checkout page . After the user validates billing fields there is a option for shipping "ship to a different adderss?" so if its checked the user has to fill shipping address if not then shipping address will be same as billing address , and here cames the error. Shipping address returns null , empry strings while billing address returns all the keyput that user has typed , how to make this work correctly? 
thanks

**Comment by anhskohbo** [comment]
Why you need "shipping address" when you rent a room in a hotel? We set room book room as a "virtual product" in woocommerce, so woocommerce will display with no shipping fields.

**Comment by itsSilver** [comment]
i need it because i have developed my own payment gateway and it is neccesary to add shipping fields , do you know any method how can i solve my problem . 
thanks

**Comment by anhskohbo** [comment]
Okay, wait a while I'll try to allow enable shipping fields.

**Comment by itsSilver** [comment]
you can tell me how to change it form virtual to a simple product because as you said for booking isnt neccessary shipping field but i need it for my custom gateway

**Comment by anhskohbo** [comment]
In `awebooking-woocommerce/inc/Product_Booking_Room.php` we declare:

```
/**
 * This is virtual product (has no shipping).
 *
 * @return true
 */
public function is_virtual() {
	return true;
}
```

I just set to `false` but seem got no luck, need looking more to see why :D

**Comment by itsSilver** [comment]
i added in my functions.php 
add_filter( 'woocommerce_cart_needs_shipping_address', '__return_true', 50 );
and i think is working now. 
Need to run a few tests and ill tell you the results .
Thanks
