### ISSUE TITLE
Cart empty after checkout from room types

### ISSUE THREAD

**Issue by itsSilver** [awethemes/awebooking#57]
Hi there , 

Im using Hillter

Version: 2.0.5

theme with latest version of awebooking beta10 and woocomerce 3.0.1 .

If i book from check avaibility form everything works fine but if i book from a room directly (after viewing a room, check avaibility , go to checkout and pay via paypal or my custom gateway) it reutrns your cart is currently empty , what is causing this issue?

Please as fast as posible

Thanks

**Comment by anhskohbo** [comment]
Track: https://awethemes.com/forum/plugin-support/awebooking/4389

**Comment by ndoublehwp** [comment]
This isn't a bug. You can follow this link: https://awethemes.com/forum/plugin-support/awebooking/4389
I think you set the wrong shortcode. In `Booking Informations` page, you need to use shortcode: `awebooking_booking` instead 'woocommerce_cart'.

**Comment by itsSilver** [comment]
I still cant get it work propperly even after i changed the shortcode , it
delivers till payment gateway and if i click pay it works but if i click
cancel & clear cart then if it try to book a room it will say cart empty



‌

**Comment by anhskohbo** [comment]
Did you have a live website so I can check that?

**Comment by itsSilver** [comment]
yes , you can check it here :
web: demo.kurseonline.al/turku/
user: thesilvervevo@gmail.com
pass: Asroma1927

Also im using qtranslate for translation and i translated room names but now they are showing really weird like : [en]rooms [sq]dhomacan you please check this too?

Thanks



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.100&pv=5.1&source=email_footer_2] On Fri, Nov 10, 2017 at 4:14pm, Nguyen Van Anh < notifications@github.com [notifications@github.com] > wrote:
Did you have a live website so I can check that?

**Comment by anhskohbo** [comment]
This's public place, please do not public any account information.

**Comment by itsSilver** [comment]
no problem this is a demo wordpress installation



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.100&pv=5.1&source=email_footer_2] On Fri, Nov 10, 2017 at 4:35pm, Nguyen Van Anh < notifications@github.com [notifications@github.com] > wrote:
This's public place, please do not public any account information.

**Comment by itsSilver** [comment]
So any idea how can we solve this?

Thanks


‌

**Comment by itsSilver** [comment]
hi there, i was able to fix this issue by adding two or more romms for every room type , i dont know which is causing this problem , our custom gateway payment or the plugin , can you take a look at our custom gateway payment and see if theres maybe an error.
