### ISSUE TITLE
Not showing room information on v. 3.1.10

### ISSUE THREAD

**Issue by Bignarem** [awethemes/awebooking#87]
After a room's search it only shows the room name, picture and bed, but the rest it is not showing (inclusions, capacity, price and book now button)

v3.1.9
![v 3 1 9](https://user-images.githubusercontent.com/35050327/46361734-5f0fab80-c63c-11e8-8f4f-73406e8be2ee.png)

v.3.1.10
![v 3 1 10](https://user-images.githubusercontent.com/35050327/46361736-5f0fab80-c63c-11e8-8aa5-873f7dcb6355.png)

**Comment by anhskohbo** [comment]
I confirm that happened when deploy into svn of wp.org. Will be rebuild new path to fix that!
